### ISSUE TITLE
Network Initialization Should be Separate from Launch

### ISSUE THREAD

**Issue by WilfredTA** [Tempest-Protocol/trampoline#1]
Currently, to start a new network you must do `trampoline network launch` within a Trampoline project.

This starts the network with the default configuration (which can be changed by manually modifying trampoline.toml & trampoline-env.toml files).

However, setting the miner requires that the network configs are first generated. So, an `init` or `new` network command should be available so that developers can configure the network with more granularity prior to launching the network.

**Comment by pLabarta** [comment]
This is resolved by #16 where launching a devchain requires an initial `trampoline net init` followed by `trampoline net start`
