### ISSUE TITLE
Separate image for indexer

### ISSUE THREAD

**Issue by WilfredTA** [Tempest-Protocol/trampoline#2]
In previous Trampoline version, indexer existed in the same image as the node. The base indexer should be run in a separate container so that it can be extended & customized.

Further, people should have the option to run the indexer as a separate process locally in the case where dapp-specific indexer logic is added.

**Comment by pLabarta** [comment]
This is partially solved in #16. Each service is run in an independent docker container using docker-compose.

Adding a new command to run only the indexer would solve this issue?
